baseURL = 'https://dasimagin.github.io/'
languageCode = 'en-us'
title = 'Robotics'

[[menu.main]]
  name = 'home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'notes'
  url = '/notes/'
  weight = 2

[params]
  author = 'Denis Simagin'
  dateFormat = 'Jan 2 2006'
  showSummary = true
  description = 'I am a software engineer with a foundation in computer science and a passion for machine learning. I am interested in a range of robotics-related topics. These notes are a collection of thoughts and research results.'
  footer = 'Love robots!'

[[params.social]]
  name = 'GitHub'
  url = 'https://github.com/dasimagin'

[[params.social]]
  name = 'LinkedIn'
  url = 'https://linkedin.com/in/denis-simagin-98627895'

[[params.social]]
  name = 'YouTube'
  url = 'https://youtube.com/@dasimagin'
